set nocompatible
set backspace=indent,eol,start
set backup
set history=50
set ruler
set showcmd
set incsearch
set mouse=a
syntax on
set hlsearch

filetype plugin indent on
autocmd FileType text setlocal textwidth=78
autocmd BufReadPost *
\ if line("'\"") > 1 && line("'\"") <= line("$") |
\   exe "normal! g`\"" |
\ endif

if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

autocmd BufNewFile,BufRead *.pde setlocal ft=arduino
autocmd BufNewFile,BufRead *.ino setlocal ft=arduino
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set expandtab
set number
set nobackup
set ignorecase
set smartcase
set foldmethod=marker
set foldcolumn=1
set hidden
set wildmenu
set cmdheight=2
